variables:
  SolutionDir: barycentrics11\build
  Solution: Barycentrics11_2015.sln

before_script:
  - 'for /f "usebackq delims=" %%i in (`vswhere.exe  -products Microsoft.VisualStudio.Product.BuildTools -property installationPath`) do set MSBUILD_PATH=%%i'
  - 'call "%MSBUILD_PATH%\VC\Auxiliary\Build\vcvars64.bat"'

stages:
  - build

build debug x64:
  tags:
  - windows
  - amd64
  stage: build
  script:
  - echo Building %Solution%
  - cd %SolutionDir%
  - 'msbuild.exe "%Solution%" /p:Configuration=Debug'

build release x64:
  tags:
  - windows
  - amd64
  stage: build
  script:
  - echo Building %Solution%
  - cd %SolutionDir%
  - 'msbuild.exe "%Solution%" /p:Configuration=Release'


