variables:
  SampleName: barycentrics11
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - deploy
build_vs2019:
  tags:
  - windows
  - amd64
  stage: build
  artifacts:
    paths:
    - barycentrics11/bin/
  script:
  - 'cmake -S %SampleName% -B %SampleName%/build/VS2019_x64 -G "Visual Studio 16 2019" -A x64'
  - 'cmake --build %SampleName%/build/VS2019_x64 --config Release'
  - 'cmake --build %SampleName%/build/VS2019_x64 --config Debug'

package_sample:
  tags:
  - windows
  - amd64
  stage: deploy
  dependencies:
    - build_vs2019
  script:
    - echo "Packaging build"
    - echo cd .\%SampleName%\bin\ > %SampleName%.bat
    - echo start %SampleName%.exe >> %SampleName%.bat
  artifacts:
      name: "%SampleName%-%CI_COMMIT_TAG%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHORT_SHA%"
      paths:
      - "%SampleName%/bin/"
      - "%SampleName%/src/shaders.hlsl"
      - "ags_lib"
      - "readme.md"
      - "license.txt"
      - "%SampleName%.bat"
